- name: Demonstration of the get_config Ansible module
  gather_facts: false
  hosts: 192.168.133.84
  tasks:
    - name: Execute the get_config RPC
      ansible.netcommon.netconf_get:
        display: native
        source: startup
      register: result
    - name: Print the configuration as JSON
      debug:
        var: result.output
